---
apiVersion: v1
kind: Namespace
metadata:
  name: blackbox-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: blackbox-exporter
  name: blackbox-exporter
---
apiVersion: v1
kind: Service
metadata:
  namespace: blackbox-exporter
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
spec:
  ports:
    - name: http
      port: 9115
      protocol: TCP
      targetPort: http
  selector:
    app: blackbox-exporter
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blackbox-exporter
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          args:
            - --config.file=/etc/blackbox-exporter/config.yaml
          image: quay.io/prometheus/blackbox-exporter:v0.25.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9115
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: 9115
              scheme: HTTP
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9115
              scheme: HTTP
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            # configuration
            - mountPath: /etc/blackbox-exporter
              name: blackbox-exporter-config
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: blackbox-exporter
      serviceAccountName: blackbox-exporter
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
        - name: blackbox-exporter-config
          configMap:
            defaultMode: 420
            name: blackbox-exporter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: blackbox-exporter
  name: blackbox-exporter-config
data:
  config.yaml: |-
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: []  # Defaults to 2xx
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  namespace: blackbox-exporter
  name: chaotic-app-ready
spec:
  interval: 5s
  jobName: blackbox-exporter
  module: http_2xx
  prober:
    scheme: http
    url: blackbox-exporter.blackbox-exporter.svc:9115
  targets:
    staticConfig:
      static:
        - http://chaotic-app.app.svc:3000/_health/ready
      labels:
        app: chaotic-app
        health: ready
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  namespace: blackbox-exporter
  name: chaotic-app-alive
spec:
  interval: 5s
  jobName: blackbox-exporter
  module: http_2xx
  prober:
    scheme: http
    url: blackbox-exporter.blackbox-exporter.svc:9115
  targets:
    staticConfig:
      static:
        - http://chaotic-app.app.svc:3000/_health/alive
      labels:
        app: chaotic-app
        health: alive
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: blackbox-exporter
  name: chaotic-app-uptime
spec:
  groups:
    - name: chaotic-app-unstable
      interval: 15s
      rules:
        - alert: ChaoticAppNotReady
          expr: avg_over_time(probe_success{app="chaotic-app"}[5m]) < 0.8
          for: 1m
          labels:
            severity: error
            namespace: "{{ $labels.namespace }}"
            app: "{{ $labels.app }}"
            health_endpoint: "{{ $labels.health}}"
          annotations:
            message: "The '{{ $labels.health}}' health endpoint has been returning too many errors"