# see https://docs.openshift.com/container-platform/4.18/observability/monitoring/configuring-user-workload-monitoring/preparing-to-configure-the-monitoring-stack-uwm.html#enabling-monitoring-for-user-defined-projects_preparing-to-configure-the-monitoring-stack-uwm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    logLevel: debug